/*
* 
* 帮助页
* */
export const ABOUT_GET_LIST = 'ABOUT_GET_LIST';

/*
* 
* 创建调查问卷页
* */
export const CREATE_QUESTIONNAIRE = 'CREATE_QUESTIONNAIRE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SET_QUESTIONNAIRE = 'SET_QUESTIONNAIRE';
export const RESET_QUESTIONNAIRE = 'RESET_QUESTIONNAIRE';

export const SAVE_QUESTIONNAIRE_TITLE = 'SAVE_QUESTIONNAIRE_TITLE';
export const SAVE_QUESTIONNAIRE_STARTER = 'SAVE_QUESTIONNAIRE_STARTER';
export const SAVE_QUESTIONNAIRE_ENDING = 'SAVE_QUESTIONNAIRE_ENDING';


export const UPDATE_QUESTION_TITLE = 'UPDATE_QUESTION_TITLE';
export const ADD_QUESTION_OPTION = 'ADD_QUESTION_OPTION';
export const DEL_QUESTION_OPTION = 'DEL_QUESTION_OPTION';
export const UPDATE_QUESTION_OPTION_VALUE = 'UPDATE_QUESTION_OPTION_VALUE';

/*
* 
* 我的调查问卷页
* */
export const CENTER_GET_QUESTIONNAIRE_LIST = 'CENTER_GET_QUESTIONNAIRE_LIST';
export const CENTER_DEL_QUESTIONNAIRE = 'CENTER_DEL_QUESTIONNAIRE';



